import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { AppConfigSchema } from "@/lib/validator";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { prompt } = await req.json();

    if (!prompt) {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
    }

    if (!process.env.GEMINI_API_KEY) {
      return NextResponse.json({ error: "GEMINI_API_KEY is missing from environment variables." }, { status: 500 });
    }

    const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

    const systemPrompt = `You are an expert software engineer generating JSON schemas for a dynamic application builder backend.
    You must output ONLY valid JSON.
    
    The schema must strictly adhere to the following interface:
    - name: string (A concise, professional app title)
    - entities: array of objects { name: string, fields: array of { name: string, type: "text" | "email" | "number" | "date" | "textarea" | "select" | "boolean", required?: boolean, options?: string[] } }
    - widgets?: array of { type: "stats" | "chart", title: string, entity?: string }

    Transform the user's prompt into the best possible JSON representation for an AppGenie app configuration.`;

    const result = await model.generateContent({
      contents: [{ role: "user", parts: [{ text: `${systemPrompt}\n\nUser Request: ${prompt}` }] }],
      generationConfig: {
        responseMimeType: "application/json",
      }
    });

    const aiText = result.response.text();
    let parsedParams;
    try {
        parsedParams = JSON.parse(aiText);
    } catch {
        // Fallback sanitize
        const rawJsonText = aiText.replace(/```(json)?/g, '').trim();
        parsedParams = JSON.parse(rawJsonText);
    }

    // Zod Guardrails Barrier
    const validation = AppConfigSchema.safeParse(parsedParams);
    if (!validation.success) {
      console.error("Zod Validation Failed:", validation.error);
      return NextResponse.json({ error: "Invalid schema generated by AI." }, { status: 400 });
    }

    return NextResponse.json(validation.data, { status: 200 });

  } catch (error: any) {
    console.error("AI Generation Error:", error);
    return NextResponse.json({ error: "Failed to process AI generation request" }, { status: 500 });
  }
}
